Rails.application.routes.draw do
  get "/" => "restaurants#index"
  get "/:id/new_order" => "orders#new_order"
  get "order/:id/join" => "patrons#new_patron"
  get "order/:id/edit" => "orders#edit_order"
  put "order/:id" => "orders#update_order"
  get "order/:id" => "orders#show_order"
  post "/:id" => "orders#create_order"
  get "order/:id/cancel" => "orders#cancel_order"
  delete "order/:id" => "orders#destroy_order"
  get "patrons/:id/edit" => "patrons#edit_patron"
  get "patrons/:id/add" => "items#new_item"
  put "patrons/:id" => "patrons#update_patron"
  post "patrons/:id" => "items#create_item"
  get "patrons/:id" => "patrons#show_patron"
  post "join/:id" => "patrons#create_patron"
  get "patrons/:id/cancel" => "patrons#cancel_patron"
  delete "patrons/:id" => "patrons#destroy_patron"
  get "items/:id" => "items#edit_item"
  put "items/:id" => "items#update_item"
  delete "items/:id" => "items#destroy_item"
  get "/:id" => "restaurants#show"
end
